# ------------------------------------------------------------------------------
# Group target to build all Python binaries in this package
# ------------------------------------------------------------------------------
filegroup(
    name = "everything",
    srcs = [
        "//src/python/tools:everything",
    ],
    visibility = ["//visibility:public"],
)
