#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Leon Pohl <leon.pohl@unibw.de>
#
# SPDX-License-Identifier: Apache-2.0
"""
Generate the Bagzel teaser GIF (assets/teaser.gif): a terminal-style
`bazel build` run of the example bags, followed by real generated dataset
samples from the example pipeline, ending on the published evaluation numbers.

Run:  python3 assets/generate_teaser.py   (from the repository root)

All layout knobs are constants below — adjust them to reposition/rescale
elements without touching the scene code.
"""
from PIL import Image, ImageDraw, ImageFont
import os

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_GIF = os.path.join(REPO, "assets", "teaser.gif")
FIGS = os.path.join(
    REPO, "processing_edges/rosbag_to_vision_dataset/src/tex/joss/figs/nuScenes"
)

# ---------------------------------------------------------------- knobs ----
CANVAS = (640, 360)          # (W, H) full GIF size
WINDOW = (24, 22, 592, 316)  # terminal window (x, y, w, h)
TITLEBAR_H = 30              # window chrome above the content area

# Sample-slide image area inside the window:
IMG_MARGIN_X = 40            # horizontal inset from the window border -> smaller images
IMG_TOP = None               # None = TITLEBAR_H + IMAGE_TOP_GAP
IMG_TOP_GAP = 24             # gap between title bar and image top
IMG_BOTTOM_GAP = 56          # gap between image bottom and the caption line
SAMPLE_H_MAX = 200           # cap for the scaled sample height (px)

SAMPLE_DURATION_MS = 1500    # per dataset-sample slide
NUMBERS_SHOWN = ("386×", "faster warm dataset builds", "7.2×", "faster incremental rebuilds")
TYPING_MS, LINE_MS = 110, 260

# Sample images actually generated by the example pipeline + captions.
SAMPLES = [
    ("cam_front.jpg", "Generated dataset sample — CAM_FRONT"),
    ("lidar_on_cam_front.jpg", "LiDAR points projected onto CAM_FRONT"),
    ("lidar_bev.jpg", "Generated dataset sample — LiDAR, Bird's-Eye-View"),
    ("cam_back.jpg", "Generated dataset sample — CAM_BACK"),
]
# ---------------------------------------------------------------- knobs ----

W, H = CANVAS
BG = (22, 22, 27)
CARD = (29, 29, 36)
CARD_BORDER = (44, 44, 56)
TXT = (232, 232, 239)
TXT_DIM = (160, 160, 174)
GREEN = (63, 185, 80)
AMBER = (245, 159, 65)
RED, YELLOW = (255, 95, 86), (255, 189, 46)

WIN = WINDOW
BODY_Y0 = WIN[1] + TITLEBAR_H
LINE_H = 17
TEXT_X = WIN[0] + 14
IMG_TOP = IMG_TOP if IMG_TOP is not None else BODY_Y0 + IMG_TOP_GAP
IMG_BOTTOM = H - IMG_BOTTOM_GAP


def font(size, bold=False):
    for suffix in ("-Bold" if bold else "", ) :
        p = "/usr/share/fonts/truetype/dejavu/DejaVuSansMono%s.ttf" % suffix
        if os.path.exists(p):
            return ImageFont.truetype(p, size)
    return ImageFont.load_default()


MONO = font(12)
MONO_BOLD = font(13, bold=True)
MONO_BIG = font(30, bold=True)
TITLEBAR = font(11)


def base_frame(title):
    img = Image.new("RGB", (W, H), BG)
    d = ImageDraw.Draw(img)
    d.rounded_rectangle(WIN, radius=10, fill=CARD, outline=CARD_BORDER, width=1)
    # inset the chrome line so it stays inside the rounded corners
    d.line(
        [(WIN[0] + 8, BODY_Y0 - 8), (WIN[0] + WIN[2] - 8, BODY_Y0 - 8)],
        fill=CARD_BORDER,
        width=1,
    )
    cx = WIN[0] + 14
    for c in (RED, YELLOW, GREEN):
        d.ellipse([cx - 4, WIN[1] + 11, cx + 4, WIN[1] + 19], fill=c)
        cx += 16
    tw = d.textlength(title, font=TITLEBAR)
    d.text((WIN[0] + (WIN[2] - tw) / 2, WIN[1] + 8), title, font=TITLEBAR, fill=TXT_DIM)
    return img, d


def draw_line(d, y, segments, cursor=False):
    x = TEXT_X
    for text, color, f in segments:
        f = f or MONO
        d.text((x, y), text, font=f, fill=color)
        x += d.textlength(text, font=f)
    if cursor:
        d.rectangle([x, y + 1, x + 7, y + 13], fill=TXT)


def terminal_frames():
    frames = []
    cmd1 = "bazel build @example_data//:"
    cmd2 = "data_pipeline_processed__nuscenes_data"
    prompt = [("$ ", AMBER, MONO_BOLD)]
    full_cmd = prompt + [(cmd1 + cmd2, TXT, None)]

    for text in [cmd1[:12], cmd1[:22], cmd1, cmd1 + cmd2[:16], cmd1 + cmd2]:
        img, d = base_frame("bagzel — bazel-cli")
        draw_line(d, BODY_Y0 + 8, prompt + [(text, TXT, None)], cursor=True)
        frames.append((img, TYPING_MS))

    lines = [
        "Analyzing: 1 target (0 packages loaded)",
        "Extracting  CAM_FRONT   -> samples/CAM_FRONT/",
        "Extracting  CAM_BACK    -> samples/CAM_BACK/",
        "Extracting  Odometry    -> vehicle/odom.csv",
        "Converting  annotations -> nuScenes metadata",
    ]
    y0 = BODY_Y0 + 8 + LINE_H * 1.6
    for i in range(len(lines) + 1):
        img, d = base_frame("bagzel — bazel-cli")
        draw_line(d, BODY_Y0 + 8, full_cmd)
        y = y0
        for text in lines[:i]:
            draw_line(d, y, [(text, TXT_DIM, None)])
            y += LINE_H
        frames.append((img, LINE_MS if i else 130))

    final_y = y0 + len(lines) * LINE_H
    img, d = base_frame("bagzel — bazel-cli")
    draw_line(d, BODY_Y0 + 8, full_cmd)
    y = y0
    for text in lines:
        draw_line(d, y, [(text, TXT_DIM, None)])
        y += LINE_H
    d.text((TEXT_X, final_y + 6), "Build completed successfully", font=MONO_BOLD, fill=GREEN)
    d.text(
        (TEXT_X, final_y + 6 + LINE_H * 1.8),
        "Incremental rebuild: only new bags re-processed, cached\n"
        "artifacts reused (nuScenes + metadata + calibration)",
        font=MONO,
        fill=TXT_DIM,
    )
    draw_line(d, final_y + 6 + LINE_H * 4.2, [("", TXT, None)], cursor=True)
    frames.append((img, 400))
    frames.append((img.copy(), 1400))
    return frames


def sample_frames():
    """Each dataset sample is a slide showing the scaled sample inside the window."""
    frames = []
    avail_w = WIN[2] - 2 * IMG_MARGIN_X
    avail_h = IMG_BOTTOM - 8 - IMG_TOP
    for name, caption in SAMPLES:
        src = Image.open(os.path.join(FIGS, name)).convert("RGB")
        r = min(avail_w / src.width, min(avail_h, SAMPLE_H_MAX) / src.height)
        im = src.resize((int(src.width * r), int(src.height * r)), Image.LANCZOS)
        img, d = base_frame("bagzel — generated dataset (nuScenes format)")
        x = WIN[0] + IMG_MARGIN_X + (avail_w - im.width) // 2
        y = IMG_TOP + max(0, (avail_h - im.height) // 2)
        img.paste(im, (x, y))
        d.rectangle(
            [x - 1, y - 1, x + im.width, y + im.height],
            outline=CARD_BORDER,
            width=1,
        )
        tw = d.textlength(caption, font=MONO)
        d.text(
            (WIN[0] + (WIN[2] - tw) / 2, H - 44),
            caption,
            font=MONO,
            fill=TXT_DIM,
        )
        print(
            f"  {name}: image {im.width}x{im.height} at (x={x}, y={y}) — "
            f"inside window ({WIN[0]}..{WIN[0]+WIN[2]}, {WIN[1]}..{WIN[1]+WIN[3]}): "
            f"{x > WIN[0] and y > BODY_Y0 - 8 and x+im.width < WIN[0]+WIN[2] and y+im.height < IMG_BOTTOM}"
        )
        frames.append((img, SAMPLE_DURATION_MS))
    return frames


def numbers_frame():
    img, d = base_frame("bagzel — reproducible by design")
    y = BODY_Y0 + 26
    d.text((TEXT_X, y), NUMBERS_SHOWN[0], font=MONO_BIG, fill=AMBER)
    d.text((TEXT_X + 120, y + 4), NUMBERS_SHOWN[1] + "\n(published evaluation, IEEE CASE 2026)",
           font=MONO, fill=TXT)
    d.text((TEXT_X, y + 82), NUMBERS_SHOWN[2], font=MONO_BIG, fill=AMBER)
    d.text((TEXT_X + 120, y + 86), NUMBERS_SHOWN[3], font=MONO, fill=TXT)
    d.text((TEXT_X, y + 160),
           "Build · cache · rebuild — reproducible datasets from ROS bags",
           font=MONO, fill=TXT_DIM)
    return img


def main():
    os.makedirs(os.path.dirname(OUT_GIF), exist_ok=True)
    frames = terminal_frames() + sample_frames()
    nf = numbers_frame()
    frames += [(nf, 1100), (nf, 1300)]

    quantized = []
    for img, dur in frames:
        q = img.quantize(colors=128, method=Image.MEDIANCUT,
                         dither=Image.Dither.FLOYDSTEINBERG)
        q.info["duration"] = dur
        quantized.append(q)
    quantized[0].save(
        OUT_GIF, save_all=True, append_images=quantized[1:],
        duration=[dur for _, dur in frames], loop=0, optimize=True,
    )
    print(f"GIF: {len(frames)} frames, {os.path.getsize(OUT_GIF) / 1024:.0f} KB -> {OUT_GIF}")


if __name__ == "__main__":
    main()
